### ISSUE TITLE
When clicking a hyperlink from within the TOS and PP, it expands the page to fit the window and there is no way out without closing Featherlite

### ISSUE THREAD

**Issue by Drakedevo** [haloplatform/platform-support-tracker#5]

**Comment by shadowcodex** [comment]
@nickmessing we should add a back option to the top menu bar of the operating system for the feather client.

@Drakedevo I assume this happens in the desktop client?

**Comment by Drakedevo** [comment]
Yes it happens in desktop and browser versions.
