### ISSUE TITLE
Monitored masternode shared contract does not update automatically

### ISSUE THREAD

**Issue by alien45** [haloplatform/platform-support-tracker#7]
Once a contract is added for monitoring it does not update added contributions. I suppose it is due to the DAPP not syncing the contract? I have closed Feather and started couple times but it´s still the same. Only way currently to update is to manually add the contract to monitoring list again.

**Comment by shadowcodex** [comment]
Can you add a screenshot of what you are experiencing please?

**Comment by alien45** [comment]
It´s been resolved already on one of the following updates. Thanks!
